### ISSUE TITLE
GItHub Action Support Advice

### ISSUE THREAD

**Issue by devorbitus** [kobaltcore/renconstruct#1]
I would like to create a GitHub Action that utilizes renConstruct to build distributions from GitHub. Right now, renConstruct will utilize an existing cache directory which I can provide through the cache GitHub action. However, the first time renConstruct is run after downloading the SDK and raft, it generates a new android Keystore without giving the opportunity to override.

I was thinking I could submit a PR to renConstruct that would allow an additional non-required option that would allow an additional path to search for tasks. The GitHub action's container would have an additional task inside like this...

```python

### Logging ###
import os
import sys
import base64
from renconstruct import logger

class OverrideAndroidKeystoreTask():

    PRIORITY = 1

    def __init__(self, name, config):
        self.name = name
        self.config = config

    @staticmethod
    def validate_config(config):
        pass

    def pre_build(self):
        logger.info('Time to do the prebuild of OverrideAndroidKeystoreTask')
        base64androidKeyfile = os.environ.get('BASE64_ANDROID_KEYSTORE_OVERRIDE','')
        if not (base64androidKeyfile and base64androidKeyfile.strip()):
            logger.error('Environment variable of BASE64_ANDROID_KEYSTORE_OVERRIDE holding the Base64 encoded Android Keystore was not found!')
            sys.exit(1)
        else:
            base64androidKeyfileDecoded = base64.b64decode(base64androidKeyfile)
            sdkVersion = self.config['renutil']['version']
            ks = open(f'./cache/{sdkVersion}/rapt/android.keystore','w')
            ks.write(base64androidKeyfileDecoded)
            ks.close()
        pass

    def post_build(self):
        pass

```
Then the command to execute renConstruct would be something like this...
```sh
renconstruct -d -i ../renpy-project -o ../renpy-project_dist -c ../renpy-project/config.yml -a ./additional-tasks
```
and that `config.yml` file would look something like this...
```yaml
tasks:
  set_extended_memory_limit: false
  notarize: false
  clean: true
  patch: false
  override_android_keystore: true

patch:
  path: "renpy-patches"

build:
  win: true
  mac: true
  android: true

renutil:
  version: "7.4.5"
  registry: "cache"

renotize:
  apple_id: fill-this-in
  password: fill-this-in
  identity: fill-this-in
  bundle: com.my-organization.my-game
  altool_extra:

```
There would be a GitHub secret added that would have the base64 encoded `android.keystore` file stored inside it and executed like this...
```yaml
- name: Build Ren'Py-based Visual Novel distributions using renConstruct
  uses: devorbitus/renconstruct-build-action@master
  with:
    sdk-version: '7.4.5'
    project-dir: '.'
    config: 'config.yml'
  env:
    BASE64_ANDROID_KEYSTORE_OVERRIDE: ${{ secrets.ANDROID_KEYSTORE }}

```

Do you think this approach is the right way to go or would it be better to make changes to renutil to allow for android keystore overrides or another suggestion I have yet to consider?
