### ISSUE TITLE
Is it possible to notarize the Mac build on Windows, or Gitlab CI?

### ISSUE THREAD

**Issue by SergioAlonsoJr** [kobaltcore/renconstruct#5]
I want to notarize the Mac version, but I don't own a Mac.

Is it possible to notarize the Mac build on Windows, or Gitlab CI?

**Comment by kobaltcore** [comment]
Yes, this is possible, but a bit cumbersome.
renconstruct actually ships with a notarization task that should be able to do this, but since Apple likes to change things rather frequently, this is not guaranteed to work in the future.

You can supply the relevant data for this via environment variables such as this in a Github Action:
```
- name: Build Project
  run: renconstruct -d -i "${{ github.workspace }}" -o "${{ github.workspace }}/../dist" -c "${{ github.workspace }}/config.yml"
  env:
    RC_APPLE_ID: ${{ secrets.RC_APPLE_ID }}
    RC_APPLE_PWD: ${{ secrets.RC_APPLE_PWD }}
    RC_SIGN_CERT: ${{ secrets.RC_SIGN_CERT }}
    RC_SIGN_CERT_PWD: ${{ secrets.RC_SIGN_CERT_PWD }}
    RC_SIGN_IDENTITY: ${{ secrets.RC_SIGN_IDENTITY }}
```

This requires the following:
- An Apple ID with a subscription to the Apple Developer Program (100$ a year)
- An App-Specific password for your Apple ID, generated via Apple's Account Profile website
- A signing certificate, generated via XCode or on the Developer Portal and exported as a .p12, then encoded as base64
- The password used for the certificate export
- The signing Identity, which is the hash code specified for the certificate

This is unfortunately very cumbersome to obtain, especially if you do not own a Mac to prepare these things in the first place.
Once they're all in place, signing on a macOS runner should be possible though.
